project:
  type: website
  output-dir: docs

website:
  title: "Benjamin Horvath"
  description: "Personal site and blog"
  favicon: "favicon.ico"
  site-url: "https://benhorvath.github.io"
  navbar:
    left:
      - text: Home
        href: index.html
      - text: Blog
        href: posts/index.html
      - text: About
        href: about.html

format:
  html:
    self-contained: false
    theme: cosmo
    css: assets/styles.css